[package]
name = "jitos-views"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
jitos-core = { path = "../jitos-core" }
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
